config/routes.rb
Rails.application.routes.draw do
  resources :books

end

app/models/author.rb
class Author < ActiveRecord::Base
end

app/models/book.rb
class Book < ActiveRecord::Base
  def publish_format()
      if self.publish_time.nil? then
         return '未記載';
      end
      return self.publish_time.strftime("%Y年 %m月 %d日");
  end
  def popular_format
      if self.popular.nil? then
         return ''
      end
      result = "";
      for num in 1..self.popular
         result += "★";
      end
      return result;
  end
end

app/models/bookshelf.rb
class Bookshelf < ActiveRecord::Base
end

app/models/study.rb
class Study
  def full_name(last, first)
    "#{last} #{first}"
  end

  def self.output
    data = <<-"EOS"
    {
      "language": "Ruby"
    }
    EOS

    puts data
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
    #@books = Book.where("name LIKE '%女%' AND author LIKE '%yang%'")
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :author, 'publish_time', 'popular')
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
    <% if @book.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

          <ul>
            <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <%= f.label :name, "名前" %><br>
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-3">
          <%= f.label :author, "作者" %><br>
          <%= f.text_field :author, class: "form-control" %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-2">
          <%= f.label :publish_time, "出版日" %><br>
          <%= f.date_select :publish_time, use_month_numbers: true,
         :start_year => 1990, :end_year => 2015, use_short_month: true, class: "form-control", id: "publish_time" %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-2">
          <%= f.label :popular, "人気度" %><br>
          <%= f.select :popular, {"★" => 1, "★★" =>2, "★★★" =>3 ,"★★★★" =>4,"★★★★★" =>5},
                       :selected => 3, class: "form-control" %>
        </div>
      </div>
      <br/>

      <div class="actions">
        <%= f.submit "新規作成", :class => "btn btn-primary" %>
      </div>
    </div>
<% end %>

app/views/books/edit.html.erb
<div class="container">
  <h1>書籍編集</h1>
</div>

<%= render 'form' %>
<div class="container">
<%= link_to '詳細', @book %> |
<%= link_to '一覧へ戻る', books_path %>
</div>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">書籍一覧</h1>

<div class="container">
<table class="table table-striped table-hover"> 
  <thead>
    <tr>
      <th>名前</th>
      <th>作者</th>
      <th>出版日</th>
　　　<th>人気度</th>
      <th colspan="3" class="col-md-3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= book.author %></td>
        <td><%= book.publish_format() %></td>
        <td><%= book.popular_format() %></td>
        <td><%= link_to '詳細', book %></td>
        <td><%= link_to '編集', edit_book_path(book) %></td>
        <td><%= link_to '削除', book, method: :delete, data: { confirm: '削除しますか?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div class="container">
<br>

<%= link_to '新規追加', new_book_path, {class: "btn btn-success", style: "color:white;"} %>
</div>

app/views/books/new.html.erb
<div class="container">  
	<h1>書籍新規作成</h1>
</div>
<%= render 'form' %>
<div class="container">  
	<%= link_to '戻る', books_path %>
</div>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>名前:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>作者:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>出版日:</strong>
  <%= @book.publish_time %>
</p>

<p>
  <strong>人気度:</strong>
  <%= @book.popular %>
</p>
<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Books</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
  <link rel="stylesheet" type="text/css" href="jquery.datetimepicker.css"/ >
  <script src="jquery.js"></script>
  <script src="jquery.datetimepicker.js"></script>

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>